---
- name: Stoping old application
  user: kadmin
  become: true
  hosts: app_server
  tasks:
    - shell: rm -rf /usr/local/tomcat7/webapps/helloworld/*
 
- name: Download & deploying Application
  user: kadmin
  become: true
  hosts: app_server
  tasks:
    - get_url:
        force: yes
        url: "{{ lookup('env','ARTIFACT_URL') }}"
        dest: "/usr/local/tomcat7/webapps/helloworld/"
    - stat: 
        path: "/usr/local/tomcat7/webapps/helloworld/"

- name: stop tomcat
  user: kadmin
  become: true
  hosts: app_server
  tasks:
    - shell: /etc/init.d/tomcat stop

- name: start tomcat
  user: kadmin
  become: true
  hosts: app_server
  tasks:
    shell: |
      cd /usr/local/tomcat7/bin  
      sudo ./catalina.sh start
