---
- name: Download & deploying Application
  user: kadmin
  become: true
  hosts: app_server
  tasks:
    - get_url:
        force: yes
        url: "{{ ARTIFACT_URL }}"
        dest: "/usr/local/tomcat7/webapps/{{ IMAGE }}.war"
    - stat: 
        path: "/usr/local/tomcat7/webapps/{{ IMAGE }}.war"

